### ISSUE TITLE
Job build

### ISSUE THREAD

**Issue by Manuja-B** [airavata-courses/Squadron#65] opened 2020-03-21 00:52 UTC
Hi,
My job build - Build no 25 failed.
Can you please check into that.

**Comment by ghost** [comment] 2020-03-21 01:09
HI Manuja,

It failed due to some network issue probably. In our helm chart, there is a dependency on Mongodb which is downloaded from the internet. Somehow, that repo was not found. Two our builds after your build passed successfully.

Save error occurred:  could not find : chart mongodb not found in https://charts.bitnami.com/bitnami
Deleting newly downloaded charts, restoring pre-update state
Error: could not find : chart mongodb not found in https://charts.bitnami.com/bitnami

**Comment by ghost** [comment] 2020-03-21 01:10
This issue was not there in it

**Comment by ghost** [comment] 2020-03-21 01:21
Closing this issue as the problem is resolved now. Build #27, #28 passed without the problem.

**Closed as completed by ghost** 2020-03-21 01:21 UTC
